"""Initial migration.

Revision ID: a854f72d0a42
Revises: 
Create Date: 2022-07-27 00:12:49.675478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a854f72d0a42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookshelves', sa.Column('created_by', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookshelves', 'created_by')
    # ### end Alembic commands ###
